require:
  - rubocop-performance
  - rubocop-rspec

inherit_gem:
  rentacop: rentacop.yml

AllCops:
  TargetRubyVersion: 2.6.0
  Exclude:
    - 'tmp/**/*'
    - 'debug.rb'
    - 'examples/**/*'
    - 'spec/approvals/**/*'
    - 'spec/fixtures/**/*'

# Allow longer lines in command DSL
Layout/LineLength:
  Exclude:
    - lib/colorly/command.rb

# Allow nameless subjects
RSpec/NamedSubject:
  Enabled: false

# Allow the first `describe` to be any text in some cases
RSpec/DescribeClass:
  Exclude:
    - 'spec/colorly/bin_errors_spec.rb'

# Allow multiple expectations
RSpec/MultipleExpectations:
  Max: 4

